---
title: "Influenza-like Illness ED Visits"
author: "Adam Whalen"
date: "11/28/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Import ED Visits dataset

We will use the pared down dataset created earlier.

```{r}
flu_visits = 
  read_csv("./ed_flu_tidy.csv")
```

Pull in zip code/borough tibble from [the web]("https://www.health.ny.gov/statistics/cancer/registry/appendix/neighborhoods.htm").

```{r, eval = FALSE}
url = "https://www.health.ny.gov/statistics/cancer/registry/appendix/neighborhoods.htm"

zip_boro_html = read_html(url)

zip_boro_df = 
  zip_boro_html %>% 
  html_nodes(css = "table") %>% 
  html_table(header = TRUE) %>% 
  colnames()
  as_tibble(rownames = c("boro", "neighborhood", "zip_code"))
  mutate(
    boro = as.character(Borough),
    neighborhood = as.character(Neighborhood),
    zip_code = as.character("Zip Codes")
  ) %>% 
  select(-Neighborhood) %>% 
  janitor::clean_names()

```




Create a map using `plotly`.

```{r}
flu_visits %>% 
  mutate(text_label = str_c(
    "Date: ", date, 
    "\n% ILI Visits: ", pct_visits,
    "\n% ILI Admissions: ", pct_adm)) %>% 
  plot_ly(
    x = ~date, y = ~total_ed_visits, color = ~mod_zcta, text = ~text_label,
    alpha = 0.3, type = "scatter", mode = "markers"
  )
```

