---
title: "Flu Vaccination Sites"
author: "Adam Whalen"
date: "11/20/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(httr)
library(rvest)
library(plotly)
library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Data Description

This data set contains information about the locations in NYC where individuals can get a flu shot.

```{r import, message = FALSE}
flu_vax = 
  GET("https://data.cityofnewyork.us/resource/w9ei-idxz.csv") %>% 
  content("parsed")
```

Tidy the set

```{r tidy}
flu_vax_tidy = 
  flu_vax %>% 
  select(objectid, facility_name, walk_in, insurance, children, borough, zip_code, latitude, longitude) %>% 
  mutate(borough = str_to_title(borough))
```

Graph it up, in `plotly`

```{r plotly, warning = FALSE}
vax_plotly = 
  flu_vax_tidy %>% 
  mutate(text_label = str_c(facility_name, "\nZip Code: ", zip_code)) %>% 
  plot_ly(
    x = ~longitude, y = ~latitude, color = ~borough,
    text = ~text_label, alpha = 0.7, type = "scatter", mode = "markers"
  ) 

vax_plotly
```

Rad. Now do it with a real map, in `leaflet`.

```{r leaflet}
vax_leaf = 
  flu_vax_tidy %>% 
  mutate(text_label = str_c(facility_name, ", ", zip_code)) %>%
  leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(lat = ~latitude, lng = ~longitude, radius = 0.1, label = ~text_label)

vax_leaf
```



